emcc \
-sEXPORT_ES6 \
-O0 \
-std=c++17 \
-I/Users/tgross/Documents/GitHub/libarchive/dist/include \
-L/Users/tgross/Documents/GitHub/libarchive/dist/lib \
-larchive \
-lembind \
./src/main.cpp \
-o ./dist/extract.js